# Generated by Django 5.2.3 on 2025-10-20 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
        ('page_professeur', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymat',
            name='annee_academique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription_pedagogique.anneeacademique'),
            preserve_default=False,
        ),
    ]
