# Generated by Django 5.2.3 on 2025-10-14 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
        ('page_professeur', '0002_initial'),
        ('utilisateurs', '0002_alter_etudiant_num_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='ues_composantes',
            field=models.ManyToManyField(blank=True, related_name='ue_parente', to='page_professeur.ue'),
        ),
        migrations.CreateModel(
            name='ResultatUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('credits_obtenus', models.IntegerField(default=0)),
                ('details_validation', models.JSONField(blank=True, null=True)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ues', to='utilisateurs.etudiant')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ues', to='inscription_pedagogique.inscription')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='page_professeur.ue')),
            ],
            options={
                'unique_together': {('etudiant', 'ue', 'inscription')},
            },
        ),
    ]
