# Generated by Django 5.2.7 on 2025-11-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0003_alter_evaluation_anonyme'),
        ('page_professeur', '0005_alter_ue_semestre'),
    ]

    operations = [
    ]
