# Generated by Django 5.2.3 on 2025-09-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_professeur', '0011_alter_evaluation_type'),
        ('utilisateurs', '0006_alter_etudiant_num_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymats', to='utilisateurs.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymats', to='page_professeur.ue')),
            ],
            options={
                'unique_together': {('etudiant', 'ue')},
            },
        ),
    ]
