# Generated by Django 5.2.3 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='titre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
