# Generated by Django 5.2.3 on 2025-11-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
    ]
