# Generated by Django 5.2.3 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('professeur', 'Professeur'), ('admin', 'Administrateur'), ('resp_notes', 'Responsable des notes'), ('resp_inscription', 'Responsable des inscriptions'), ('secretaire', 'Secrétaire'), ('gestionnaire', 'Gestionnaire')], max_length=30),
        ),
    ]
