# Generated by Django 5.2.3 on 2025-12-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_doit_changer_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naiss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
