# Generated by Django 5.2.3 on 2025-10-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestionnaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
