# Generated by Django 5.2.3 on 2025-10-17 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_gestionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionnaire',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('professeur', 'Professeur'), ('admin', 'Administrateur'), ('resp_notes', 'Responsable des notes'), ('resp_inscription', 'Responsable des inscriptions'), ('secretaire', 'Secrétaire'), ('gestionnaire', 'Gestionnaire'), ('chef_dpt', 'Chef de département')], max_length=30),
        ),
        migrations.CreateModel(
            name='ChefDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_dpt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
