# Generated by Django 5.2.3 on 2025-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
    ]
