# Generated by Django 5.2.3 on 2025-10-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
