# Generated by Django 5.2.3 on 2026-01-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0002_initial'),
        ('utilisateurs', '0002_alter_professeur_titre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importetudiant',
            options={'ordering': ['-date_import'], 'verbose_name': 'Historique des opérations étudiants', 'verbose_name_plural': 'Historique des opérations étudiants'},
        ),
        migrations.RemoveField(
            model_name='importetudiant',
            name='type_fichier',
        ),
        migrations.AddField(
            model_name='importetudiant',
            name='methode',
            field=models.CharField(choices=[('manuel', 'Création manuelle'), ('import', 'Import fichier'), ('suppression', 'Suppression étudiant')], default='manuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_etudiants', to='utilisateurs.respinscription'),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='date_import',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='imports_etudiants/'),
        ),
    ]
