# Generated by Django 5.2.3 on 2025-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0003_alter_semestre_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeetude',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
