# Generated by Django 5.2.3 on 2025-12-02 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0003_importetudiant'),
        ('utilisateurs', '0002_utilisateur_doit_changer_mdp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importetudiant',
            options={'ordering': ['-date_import'], 'verbose_name': 'Historique création étudiant', 'verbose_name_plural': 'Historique créations étudiants'},
        ),
        migrations.RemoveField(
            model_name='importetudiant',
            name='type_fichier',
        ),
        migrations.AddField(
            model_name='importetudiant',
            name='methode',
            field=models.CharField(choices=[('manuel', 'Création manuelle'), ('csv', 'Import CSV'), ('xlsx', 'Import Excel'), ('pdf', 'Import PDF')], default='manuel', max_length=10),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_etudiants', to='utilisateurs.respinscription'),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importetudiant',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='imports_etudiants/'),
        ),
    ]
