# Generated by Django 5.2.7 on 2025-11-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_pedagogique', '0003_anneeacademique_est_active'),
        ('inscription_pedagogique', '0005_alter_anneeetude_semestre_alter_filiere_parcours'),
    ]

    operations = [
    ]
